# Generated by Django 4.0.4 on 2022-05-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authors', '0001_initial'),
        ('Genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='No more 100 chars', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('about', models.TextField(blank=True, help_text='No more 500 words', max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='books/%Y/%m/%d/')),
                ('count_views', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_author', to='Authors.author')),
                ('genre', models.ManyToManyField(blank=True, related_name='book_genre', to='Genres.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
