# Generated by Django 4.0.4 on 2022-06-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-hit_count_generic__hits']},
        ),
    ]
