# Generated by Django 4.0.4 on 2022-05-19 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Books', '0002_userbookrelative'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBookRelative',
            new_name='UserBookRelation',
        ),
    ]
