# Generated by Django 4.0.4 on 2022-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='bookmarks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Plan to read'), (2, 'Reading'), (3, 'Read'), (4, 'Abandoned')], default=None, null=True),
        ),
    ]
