# Generated by Django 4.0.4 on 2022-05-20 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Books', '0004_book_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(related_name='book_readers', through='Books.UserBookRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
