# Generated by Django 4.0.4 on 2022-05-20 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Genres', '0001_initial'),
        ('Books', '0005_alter_book_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='book_genres', to='Genres.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(related_name='books', through='Books.UserBookRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
