# Generated by Django 4.0.4 on 2022-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_userbookrelation_bookmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='comment_time_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Horrible'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Very well')], default=None, null=True),
        ),
    ]
