# Generated by Django 4.0.4 on 2022-05-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_userbookrelation_comment_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='comment_disliked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='comment_liked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
