# Generated by Django 4.0.4 on 2022-05-31 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Books', '0009_remove_userbookrelation_comment_disliked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=800)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbookrelation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='userbookrelation',
            name='comment_disliked',
        ),
        migrations.RemoveField(
            model_name='userbookrelation',
            name='comment_liked',
        ),
        migrations.RemoveField(
            model_name='userbookrelation',
            name='comment_time_created',
        ),
        migrations.RemoveField(
            model_name='userbookrelation',
            name='like',
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='Books.CommentBook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book'),
        ),
        migrations.AddField(
            model_name='commentbook',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentbook',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
