# Generated by Django 4.0.4 on 2022-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_commentbook_remove_userbookrelation_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbook',
            name='body',
            field=models.TextField(max_length=800),
        ),
    ]
