# Generated by Django 4.0.4 on 2022-06-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0001_initial'),
        ('Books', '0011_alter_commentbook_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_author', to='Authors.author'),
        ),
    ]
