# Generated by Django 4.0.4 on 2022-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0012_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='default/book/default_book_cover_2015.jpg', upload_to='books/%Y/%m/%d/'),
        ),
    ]
