# Generated by Django 4.0.4 on 2022-06-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0013_alter_book_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count_views',
        ),
    ]
