# Generated by Django 4.0.4 on 2022-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0014_remove_book_count_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_category',
            field=models.CharField(choices=[('12', '12+'), ('14', '14+'), ('16', '16+'), ('18', '18+')], default='12', max_length=3),
        ),
    ]
