version: '3.7'

services:
  web:
    build: 
      context: src/
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/book-site/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - djangonetwork
  db:
    image: postgres:14-alpine3.16
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - djangonetwork
  redis:
    image: redis:alpine
    networks:
      - djangonetwork

volumes:
  postgres_data:

networks:
    djangonetwork:
        driver: bridge
