version: '3.9'

services:
  web:
    build: 
      context: src/
      dockerfile: Dockerfile.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/book-site/staticfiles
      - media_volume:/usr/src/book-site/media
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - djangonetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - static_volume:/usr/src/book-site/staticfiles
      - media_volume:/usr/src/book-site/media
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

    ports:
      - 8080:80
      - 4430:443
    depends_on:
      - web
    networks:
      - djangonetwork

  redis:
    image: redis:alpine
    networks:
      - djangonetwork

  db:
    image: postgres:14-alpine3.16
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - djangonetwork

volumes:
  postgres_data:
  certs:
  certs-data:
  static_volume:
  media_volume:

networks:
  djangonetwork:
    driver: bridge
