version: '3.7'

services:
  web:
    build: 
      context: src/
      dockerfile: Dockerfile.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config gunicorn_config.py aurigaone.wsgi:application"
    volumes:
      - ./src:/usr/src/book-site/
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - djangonetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - djangonetwork

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'

  db:
    image: postgres:14-alpine3.16
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - djangonetwork

volumes:
  postgres_data:
  certs:
  certs-data:

networks:
  djangonetwork:
    driver: bridge
