# Generated by Django 4.0.4 on 2022-06-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('12', '12+'), ('14', '14+'), ('16', '16+'), ('18', '18+')], default='12', max_length=3),
        ),
    ]
