# Generated by Django 4.0.4 on 2022-06-28 13:17

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='No more 100 chars', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('photo', models.ImageField(default='default/author/author.png', upload_to='authors/%Y/%m/%d')),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-hit_count_generic__hits',),
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
