# Generated by Django 4.0.4 on 2024-05-21 12:36

import django.core.validators
from django.db import migrations, models
import hitcount.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='No more 255 chars', max_length=255, validators=[django.core.validators.ProhibitNullCharactersValidator])),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('photo', models.ImageField(default='default/author/author.png', upload_to='authors/%Y/%m/%d')),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-hit_count_generic__hits',),
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
