# Generated by Django 4.0.4 on 2022-06-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, help_text='No more 100 chars', max_length=255),
        ),
    ]
