# Generated by Django 4.0.4 on 2022-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0002_alter_author_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='default/book/author.png', upload_to='authors/%Y/%m/%d'),
        ),
    ]
