# Generated by Django 4.0.4 on 2022-06-29 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_alter_book_name_alter_book_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_notification', models.TextField(max_length=500)),
                ('time', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
