version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.staging
    volumes:
      - .:/usr/src/book-site/
    ports:
      - 8000:8000
    env_file:
      - ./config/settings/.env.dev
    depends_on:
      - db
  db:
    image: postgres:14-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data: